symlink: use symbolic link
originally, I used hard link by accident breaking versioning & relative file references

diff --git a/symlink b/symlink
--- a/symlink
+++ b/symlink
@@ -5,10 +5,9 @@ if [[ ! -z "$1" ]]; then
 	HOST=$1
 fi
 
-if [[ ! -e "hosts/$HOST/configuration.nix" ]] || [[ ! -e "hosts/$HOST/hardware-configuration.nix" ]]; then
-	echo "missing $HOST.nix or $HOST-hardware.nix" >&2
+if [[ ! -e "hosts/$HOST/configuration.nix" ]]; then
+	echo "missing hosts/$HOST/configuration.nix" >&2
 	exit 1
 fi
 
-ln -f "hosts/$HOST/configuration.nix" .
-ln -f "hosts/$HOST/hardware-configuration.nix" .
+ln -sf "hosts/$HOST/configuration.nix" .
